import { MainNav } from "@/components/main-nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import prismadb from "@/lib/prismadb";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locations = await prismadb.location.findMany({
    orderBy: {
      createdAt: "desc",
    },
  });

  const formattedLocations = locations.map((item) => {
    return {
      id: item.id,
      name: item.name,
    };
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster containerStyle={{ zIndex: 9999 }} />
        <MainNav data={formattedLocations} />
        {children}
      </body>
    </html>
  );
}
